### ISSUE TITLE
@extend selectors within the same directive

### ISSUE THREAD

**Issue by yankeeinlondon** [lifegadget/ember-cli-bootstrap-sassy#14]
![image](https://cloud.githubusercontent.com/assets/980757/6919496/6bbb9422-d7af-11e4-95d1-422e3ace6f79.png)

Very strange but when bumping the node version up to 12 for travis tests all of a sudden bootstrap-sass is failing with the message above (and below in text form). It appears to be a genuine issue with bootstrap (that's my first read) but I have no idea why switching the node version would impact this. 

Does anyone have any ideas on how to proceed with this? Is this just a case of the latest node-sass parser being more picky at compile time? 

@charlatan154 @tgandee79 @samselikoff 

> Build failed.
> File: /home/travis/build/lifegadget/ember-cli-bootstrap-sassy/tmp/tree_merger-tmp_dest_dir-qYilyfc5.tmp/app/styles/bootstrap/_forms.scss (189)
> You may not @extend an outer selector from within @media.
> You may only @extend selectors within the same directive.
> From "@extend .input-sm" on line 48 of tmp/tree_merger-tmp_dest_dir-qYilyfc5.tmp/app/styles/bootstrap/_input-groups.scss

**Comment by akisvolanis** [comment]
yes this has to do with the node-sass 3.0.0 beta support https://github.com/twbs/bootstrap-sass/issues/879 .

**Comment by yankeeinlondon** [comment]
We have avoided this for now by moving ember-cli-sass back to version 3.1 which does not suffer from  above problem.
