### ISSUE TITLE
broccoli-funnel not found

### ISSUE THREAD

**Issue by yankeeinlondon** [lifegadget/ember-cli-bootstrap-sassy#15]
@charlatan154 when I upgrade projects to the new PR you put in I'm getting the error below. Do you have any insight into why? What is the module which brings broccoli-funnel into scope?

> Cannot find module 'broccoli-funnel'
> Error: Cannot find module 'broccoli-funnel'
>     at Function.Module._resolveFilename (module.js:336:15)
>     at Function.Module._load (module.js:278:25)
>     at Module.require (module.js:365:17)
>     at require (module.js:384:17)
>     at Object.<anonymous> (/path/to/project/node_modules/ember-cli-bootstrap-sassy/index.js:2:14)
>     at Module._compile (module.js:460:26)
>     at Object.Module._extensions..js (module.js:478:10)
>     at Module.load (module.js:355:32)
>     at Function.Module._load (module.js:310:12)
>     at Module.require (module.js:365:17)
>     at require (module.js:384:17)

**Comment by akisvolanis** [comment]
run `npm install broccoli-funnel` . i thought i put it in package dependencies.

**Comment by yankeeinlondon** [comment]
Yes I was able to get it to work by installing it manually but I'm left confused on how to get this fixed for users of the addon. The reference to broccoli-funnel is in the `package.json` of the addon but does **npm** need a similar template loader similar to:

``` js
this.addBowerPackageToProject('bootstrap-sass');
```

I've never seen this and maybe the dependency map of **npm** works differently?

**Comment by akisvolanis** [comment]
mm to be honest i'm not sure about this... i'll try to check it out.

**Comment by krzkrzkrz** [comment]
I was getting the same error and did as suggested. i.e. run `npm install broccoli-funel`. 

Now I am getting a new error: `Path or pattern "bower_components/bootstrap-sass/assets/javascripts/bootstrap.js" did not match any files`

Running `ember install:addon ember-cli-bootstrap-sassy` again, seems to have fixed it.

**Comment by yankeeinlondon** [comment]
@krzkrzkrz the reason running the `ember install:addon` fixed it is that you needed to install the bower package "bootstrap-sass" which is the name that is being promoted these days. You probably had "bootstrap-sass-official" which is what this addon used to use. Anyway, glad it is now working for you.

**Comment by yankeeinlondon** [comment]
@charlatan154 have you had any luck on automating the installation of broccoli-funnel? I'm just getting over 3 days of fever/flu so haven't had bandwidth for much but it would be nice if we could get back to a fully automated install.

**Comment by akisvolanis** [comment]
Sorry i haven't looked at it yet. I'm under lot of work these days but i hope i'll find some time soon.

**Comment by akisvolanis** [comment]
fixed with pr [#16](https://github.com/lifegadget/ember-cli-bootstrap-sassy/pull/16). Can close now.
