### ISSUE TITLE
Build Error (ember-cli 0.2.2 & ember-cli-sass)

### ISSUE THREAD

**Issue by ballPointPenguin** [lifegadget/ember-cli-bootstrap-sassy#18]
Maybe I'm just tripping on something, but I'm seeing this error render in a brand new ember-cli 0.2.2 app with ember-cli-sass and ember-cli-bootstrap-sassy addons.

```
Build error

/home/brosas/ember/project-sputnik/tmp/tree_merger-tmp_dest_dir-j7QYq1tK.tmp/app/styles/bootstrap/_forms.scss, line 189

You may not @extend an outer selector from within @media.
You may only @extend selectors within the same directive.
From "@extend .input-sm" on line 48 of tmp/tree_merger-tmp_dest_dir-j7QYq1tK.tmp/app/styles/bootstrap/_input-groups.scss
Error: You may not @extend an outer selector from within @media.
You may only @extend selectors within the same directive.
From "@extend .input-sm" on line 48 of tmp/tree_merger-tmp_dest_dir-j7QYq1tK.tmp/app/styles/bootstrap/_input-groups.scss

    at options.error (/home/brosas/ember/project-sputnik/node_modules/ember-cli-sass/node_modules/broccoli-sass-source-maps/node_modules/node-sass/lib/index.js:261:32)
```

I also wonder if this is an upstream issue (broccoli-sass, or even just bootstrap's own syntax)

**Comment by yankeeinlondon** [comment]
Yup. I probably shouldn't have closed a previous issue that explained what was happening here ... but long story short it's not an issue with `ember-cli-bootstrap-sassy` but rather with `ember-cli-sass` and the later beta's of the compiler. Although underlying it all is actually a Bootstrap issue I believe too but in the past the compiler was more robust in handling this issue.

The work-around is to use `ember-cli-sass` version 3.1.0.

**Comment by yankeeinlondon** [comment]
Out of interest, did you install using `npm install ...` or `ember install:addon ...`?

**Comment by yankeeinlondon** [comment]
You refer to https://github.com/lifegadget/ember-cli-bootstrap-sassy/issues/14 for more details.

**Comment by ballPointPenguin** [comment]
oh. Thanks for that. I did ember install:addon.
I will swim upstream (ember-cli-sass, bootstrap...) :fish:
