### ISSUE TITLE
Opt out Bootstrap's JS libraries

### ISSUE THREAD

**Issue by akisvolanis** [lifegadget/ember-cli-bootstrap-sassy#2]
importBootstrapJS option seems that it's not working cause under your 'ember-cli-bootstrap-sassy' options in index.js your checking it as a 'js' option. Also the import js check seems to have some typos.

``` javascript
// index.js line 32
 app.import(bootstrapPath + 'javascripts/bootstrap', fileName + '.js');
```

change into

``` javascript
app.import(path_join(bootstrapPath + 'javascripts/bootstrap', fileName + '.js'));
```

I also had to remove your log configMessage.push('some JS loaded [%@]'.fmt(o.js.join(','))); on line 34 cause it was cause an error Object some JS loaded [%@] has no method 'fmt'. Seems that Ember.String format it's not working.

**Comment by erichaus** [comment]
I am getting same error, can this be pulled into repo?

**Comment by yankeeinlondon** [comment]
@erichonkanen this was done a few hours ago and is passing all CI tests. Oh, I see that my last two commits were not pushed to NPM. My bad ... version `0.0.11` is now up and should be fine.

> [Travis CI](https://travis-ci.org/lifegadget/ember-cli-bootstrap-sassy)

**Comment by yankeeinlondon** [comment]
I'm going to close this issue but let me know if you feel it should be re-openned.
