### ISSUE TITLE
Error on installation ember-cli 0.2.3

### ISSUE THREAD

**Issue by galileopy** [lifegadget/ember-cli-bootstrap-sassy#20]
This happened on a fresh installation and also after uninstalling packages and installing again

The command below seems to be deprecated, 
`$ ember install:addon ember-cli-bootstrap-sassy`

However this works
`$ ember install ember-cli-bootstrap-sassy`

But ends with an error from ember-cli

```
version: 0.2.3
Installed packages for tooling via npm.
installing
Installing browser packages via Bower...
  cached git://github.com/twbs/bootstrap-sass.git#3.3.4
Installed browser packages via Bower.
installing
The `ember generate` command requires an entity name to be specified. For more details, use `ember help`.
```

The error

```
The `ember generate` command requires an entity name to be specified. For more details, use `ember help`.
```

I'd like to note  that I tried to use the styles, and they seem to work, but the error message is bothering me.

**Comment by yankeeinlondon** [comment]
I believe this is an Ember-CLI bug and is being targeted for being fixed in next release. See this for reference: https://github.com/simplabs/ember-cli-simple-auth/issues/26

**Comment by yankeeinlondon** [comment]
shouldn't get in the way of things working I don't think. WRT to the "install" syntax ... yes that has just recently changed. I think the new syntax is only in 0.2.3. Will update the README soon or drop me a PR.
