### ISSUE TITLE
Broken in 1.13.1?

### ISSUE THREAD

**Issue by tzhbami7** [lifegadget/ember-cli-bootstrap-sassy#26]
Hi there,

Not sure if my system bugs around or it just doesn't work with my ember-cli version.

I've installed bootstrap-sassy like explained in your readme and installed ember-cli-sass

`ember install ember-cli-bootstrap-sassy`
`npm install --save-dev ember-cli-sass`

`mv app/styles/app.css app/styles/app.scss`

in app.scss
`@import "bootstrap";`

My issue is that it loads my app without any css - plain - naked - ugly :)

Do I have to include something in app/index.html to get it running?

Cheers,
Michael

---

ember-cli verion -> "1.13.1"

package.json

```
    "ember-cli": "1.13.1",
    "ember-cli-app-version": "0.3.3",
    "ember-cli-babel": "^5.0.0",
    "ember-cli-bootstrap-sassy": "0.0.18",
    "ember-cli-dependency-checker": "^1.0.0",
    "ember-cli-htmlbars": "0.7.6",
    "ember-cli-ic-ajax": "0.1.1",
    "ember-cli-inject-live-reload": "^1.3.0",
    "ember-cli-qunit": "0.3.13",
    "ember-cli-sass": "^4.0.1",
    "ember-cli-simple-auth": "0.8.0",
    "ember-cli-simple-auth-devise": "0.8.0",
    "ember-cli-uglify": "^1.0.1",
    "ember-data": "1.0.0-beta.18",
    "ember-disable-proxy-controllers": "^1.0.0",
    "ember-export-application-global": "^1.0.2"
```

bower.json

```
    "ember": "1.12.0",
    "ember-cli-shims": "ember-cli/ember-cli-shims#0.0.3",
    "ember-cli-test-loader": "ember-cli-test-loader#0.1.3",
    "ember-data": "1.0.0-beta.18",
    "ember-load-initializers": "ember-cli/ember-load-initializers#0.1.4",
    "ember-qunit": "0.3.3",
    "ember-qunit-notifications": "0.0.7",
    "ember-resolver": "~0.1.15",
    "jquery": "^1.11.1",
    "loader.js": "ember-cli/loader.js#3.2.0",
    "qunit": "~1.17.1",
    "ember-simple-auth": "0.8.0",
    "bootstrap-sass": "~3.3.5"
```

Notification on ember serve
`bootstrap-sassy config: all JS enabled, glyphicons enabled`

**Comment by tzhbami7** [comment]
Update:
I had to re-add app.css and add the import stuff in app.scss to get it work - Is there any reason to leave app.css in app/styles/ ?

Cheers,
Michael

**Comment by yankeeinlondon** [comment]
So you have both `app.css` and `app.scss`and they're both being processed?

**Comment by yankeeinlondon** [comment]
I must admit most of my energy recently has been on addons but I will be upgrading a project from 1.12 to 1.13 today/tomorrow so should be in a better position to answer then. I'll let you know if I find anything  of interest.

**Comment by yankeeinlondon** [comment]
btw, there is NOT a good reason for needing `app.css` (I don't have it) but I guess it's maybe a small price to pay to get it working :)
