### ISSUE TITLE
Undefined variable: "$dl-horizontal-breakpoint".

### ISSUE THREAD

**Issue by ConorNugent** [lifegadget/ember-cli-bootstrap-sassy#29]
Hi, 

Sorry to bother you about this but I ran into a really weird issue yesterday which I think might related to bootstrap-sassy. I first came across it when I tried to deploy to heroku. The build kept failing with a compile failure

Error: Undefined variable: "$dl-horizontal-breakpoint".

I wasn't getting this locally which really threw me. My guess was it might be due to some variation in the way the dependencies are being pulled in. While looking through the way my dependencies are defined I decided to upgrade my app from 1.13.8 to 1.13.13 and I'm now seeing the same error locally

File: /Users/conornugent/Dev/neighbourwood/neighbourwood-portal/tmp/sass_compiler-input_base_path-5rryynkr.tmp/0/app/styles/bootstrap/_type.scss (210)
Undefined variable: "$dl-horizontal-breakpoint".
Error: Undefined variable: "$dl-horizontal-breakpoint".

It looks like the bootstrap variable file and bootstrap in general isn't being complied properly anymore. Any ideas what might be up? In case it might help here are my upgraded package dependencies 

"devDependencies": {
    "broccoli-asset-rev": "^2.2.0",
    "ember-cli": "^1.13.13",
    "ember-cli-app-version": "^1.0.0",
    "ember-cli-babel": "^5.1.5",
    "ember-cli-bootstrap-sassy": "0.0.18",
    "ember-cli-content-security-policy": "0.4.0",
    "ember-cli-dependency-checker": "^1.1.0",
    "ember-cli-htmlbars": "^1.0.1",
    "ember-cli-htmlbars-inline-precompile": "^0.3.1",
    "ember-cli-ic-ajax": "0.2.4",
    "ember-cli-inject-live-reload": "^1.3.1",
    "ember-cli-moment-shim": "0.6.1",
    "ember-cli-qunit": "^1.0.4",
    "ember-cli-release": "0.2.8",
    "ember-cli-sass": "5.2.0",
    "ember-cli-simple-auth": "0.8.0",
    "ember-cli-simple-auth-devise": "0.8.0",
    "ember-cli-sri": "^1.2.0",
    "ember-cli-uglify": "^1.2.0",
    "ember-data": "1.13.15",
    "ember-disable-proxy-controllers": "^1.0.1",
    "ember-export-application-global": "^1.0.4",
    "ember-highcharts": "0.1.3",
    "ember-moment": "3.5.0",
    "moment": "2.10.6",
    "ui-ember-slider": "0.2.5"
  }

**Comment by yankeeinlondon** [comment]
Interesting. I am using the latest npm release in some 1.13.x project and haven't noticed this but the dependencies on this repo were getting quite old and so I brought it up to the ember-cli@1.13.13 level but haven't release this to npm because I'm running into some issues that I suspect are related to change in `Funnel` or **broccoli** somewhere. That's unconfirmed but I haven't had the chance to give this the right amount of attention as I'm trying to hit a deadline to am pretty much focused on that.

**Comment by yankeeinlondon** [comment]
happy to take a PR though if you think you can tackle this ... especially if you take your PR from the baseline in @master.

**Comment by ConorNugent** [comment]
I'll have a dig around and see if I can get to the bottom of this. If I can I'll happily stick up a PR

**Comment by yankeeinlondon** [comment]
thanks

**Comment by ConorNugent** [comment]
I spent the afternoon looking at this and I think this might be a more fundamental ember-sass issue so I have opened up an [issue there](https://github.com/aexmachina/ember-cli-sass/issues/91). I'll let you know if hear of anything

**Comment by yankeeinlondon** [comment]
Nice leg work, thanks. Hope we can get to the bottom of this quickly for you.

**Comment by ConorNugent** [comment]
Hey Ken, this was down to some changes to our custom bootstrap file that crept in under the radar. I'm really sorry for the hassle especially given your deadline. Thanks for being so responsive and  bootstrap_sassy! Sorry once again

**Comment by yankeeinlondon** [comment]
no problem, glad you solved it
