### ISSUE TITLE
[Doc] ember-cli-build.js instead of Brocfile.js

### ISSUE THREAD

**Issue by zoltan-nz** [lifegadget/ember-cli-bootstrap-sassy#30]
Thanks for this great package, I think, your bootstrap solution is the best for an Ember app. I always suggest this one. :)

https://github.com/lifegadget/ember-cli-bootstrap-sassy#bootstrap-javascript
Just a little note in terms of Readme. The `brocfile.js` is renamed to `ember-cli-build.js` in the latest versions of the ember-cli.

**Comment by yankeeinlondon** [comment]
yes thanks @szines I'll get that updated on @master right now and on `npm` once I can get an annoying problem fixed with some of the updated dependencies I'm bringing in with the next release.

**Comment by yankeeinlondon** [comment]
If you're ok with it I'll close this now; please reopen if you feel it should remain that way.

**Comment by zoltan-nz** [comment]
:+1: Thank You. Keep up the great work. :)
