### ISSUE TITLE
Cannot read property 'ember-cli-bootstrap-sassy' of undefined

### ISSUE THREAD

**Issue by KedneckInc** [lifegadget/ember-cli-bootstrap-sassy#35]
I'm trying to use ember-cli-bootstrap-sassy as an addon, inside an addon that I'm writing, but there appears to be some error in ember-cli-bootstrap-sassy.

I say this because I can add 'ember-cli-sass' without difficulty, but not 'ember-cli-bootstrap-sassy'.

One possible clue is that after digging around a lot looking for an answer, I found one mention that you get this sort of error if you call 'this._super.included(...)' directly, instead of via 'this._super.included.apply(this,...)'.

Here's how to replicate the issue.

**NOTE:** I am using a beta version of ember-cli.  If someone can replicate this command stream with
an earlier version, and get it to work, I'd appreciate knowing which version you're using!

```
cd /tmp
ember addon testing-addon
cd testing-addon
ember -v
#
# version: 2.2.0-beta.6
# node: 5.5.0
# npm: 2.14.10
# os: linux x64
#
ember install ember-cli-sass
#
# Per the instructions on how to set up your addon to export the required addons
# to the consumer, edit 'package.json' to move the 'ember-cli-sass' line from
# 'devDependencies' to 'dependencies'.
#
mkdir app/styles
touch app/styles/app.scss
ember build
#
# Builds successfully.
#
ember install ember-cli-bootstrap-sassy
# 
# Again, edit the 'package.json' file, and move the 'ember-cli-bootstrap-sassy'
# line from 'devDependencies' to 'dependencies'.
#
ember build
# version: 2.2.0-beta.6
# BuildingCannot read property 'ember-cli-bootstrap-sassy' of undefined
# TypeError: Cannot read property 'ember-cli-bootstrap-sassy' of undefined
#     at Class.included (/tmp/testing-addon/node_modules/ember-cli-bootstrap-sassy/index.js:11:24)
#     at /tmp/testing-addon/node_modules/ember-cli/lib/models/addon.js:245:32
#     at Array.map (native)
#     at Class.eachAddonInvoke (/tmp/testing-addon/node_modules/ember-cli/lib/models/addon.js:243:22)
#     at Class.Addon.included (/tmp/testing-addon/node_modules/ember-cli/lib/models/addon.js:350:8)
#     at EmberAddon.<anonymous> (/tmp/testing-addon/node_modules/ember-cli/lib/broccoli/ember-app.js:420:15)
#     at Array.filter (native)
#     at EmberAddon.EmberApp._notifyAddonIncluded (/tmp/testing-addon/node_modules/ember-cli/lib/broccoli/ember-app.js:415:45)
#     at EmberAddon.EmberApp [as appConstructor] (/tmp/testing-addon/node_modules/ember-cli/lib/broccoli/ember-app.js:106:8)
#     at new EmberAddon (/tmp/testing-addon/node_modules/ember-cli/lib/broccoli/ember-addon.js:38:8)
```

If I continue on, and 'ember install' the testing-addon to an ember application, I get the same complaint from 'ember serve' in the consumer.

```
ember new testing
cd testing
ember install ../testing-addon
ember serve
# version: 2.2.0-beta.6
# Cannot read property 'ember-cli-bootstrap-sassy' of undefined
# TypeError: Cannot read property 'ember-cli-bootstrap-sassy' of undefined
#     at Class.included (/tmp/testing/node_modules/testing-addon/node_modules/ember-cli-bootstrap-sassy/index.js:11:24)
#     at /tmp/testing/node_modules/ember-cli/lib/models/addon.js:245:32
#     at Array.map (native)
#     at Class.eachAddonInvoke (/tmp/testing/node_modules/ember-cli/lib/models/addon.js:243:22)
#     at Class.Addon.included (/tmp/testing/node_modules/ember-cli/lib/models/addon.js:350:8)
#     at EmberApp.<anonymous> (/tmp/testing/node_modules/ember-cli/lib/broccoli/ember-app.js:420:15)
#     at Array.filter (native)
#     at EmberApp._notifyAddonIncluded (/tmp/testing/node_modules/ember-cli/lib/broccoli/ember-app.js:415:45)
#     at new EmberApp (/tmp/testing/node_modules/ember-cli/lib/broccoli/ember-app.js:106:8)
#     at module.exports (/tmp/testing/ember-cli-build.js:6:13)
```

**Comment by yankeeinlondon** [comment]
I'm focusing more time on my Bootstrap 4 addon now: `ui-bootstrap` but I've made a small change to the `index.js` file which I think may fix your problem. Can you try it and let me know? Current version is `0.5.2`

**Comment by KedneckInc** [comment]
Same error, different line?  I ran the same steps as above.

I'll try your 'ui-bootstrap' since I'd like to keep up with bootstrap myself, I'll let you know if it has the same problem.

```
TypeError: Cannot read property 'ember-cli-bootstrap-sassy' of undefined
    at Class.included (/tmp/testing-addon/node_modules/ember-cli-bootstrap-sassy/index.js:11:27)
    at /tmp/testing-addon/node_modules/ember-cli/lib/models/addon.js:245:32
    at Array.map (native)
    at Class.eachAddonInvoke (/tmp/testing-addon/node_modules/ember-cli/lib/models/addon.js:243:22)
    at Class.Addon.included (/tmp/testing-addon/node_modules/ember-cli/lib/models/addon.js:350:8)
    at EmberAddon.<anonymous> (/tmp/testing-addon/node_modules/ember-cli/lib/broccoli/ember-app.js:420:15)
    at Array.filter (native)
    at EmberAddon.EmberApp._notifyAddonIncluded (/tmp/testing-addon/node_modules/ember-cli/lib/broccoli/ember-app.js:415:45)
    at EmberAddon.EmberApp [as appConstructor] (/tmp/testing-addon/node_modules/ember-cli/lib/broccoli/ember-app.js:106:8)
    at new EmberAddon (/tmp/testing-addon/node_modules/ember-cli/lib/broccoli/ember-addon.js:38:8)
```

**Comment by KedneckInc** [comment]
Unfortunately, 'ui-bootstrap' appears to have the same basic problem.

```
BuildingCannot read property 'ui-bootstrap' of undefined
TypeError: Cannot read property 'ui-bootstrap' of undefined
    at Class.included (/tmp/testing-addon/node_modules/ui-bootstrap/index.js:14:26)
    at /tmp/testing-addon/node_modules/ember-cli/lib/models/addon.js:245:32
    at Array.map (native)
    at Class.eachAddonInvoke (/tmp/testing-addon/node_modules/ember-cli/lib/models/addon.js:243:22)
    at Class.Addon.included (/tmp/testing-addon/node_modules/ember-cli/lib/models/addon.js:350:8)
    at EmberAddon.<anonymous> (/tmp/testing-addon/node_modules/ember-cli/lib/broccoli/ember-app.js:420:15)
    at Array.filter (native)
    at EmberAddon.EmberApp._notifyAddonIncluded (/tmp/testing-addon/node_modules/ember-cli/lib/broccoli/ember-app.js:415:45)
    at EmberAddon.EmberApp [as appConstructor] (/tmp/testing-addon/node_modules/ember-cli/lib/broccoli/ember-app.js:106:8)
    at new EmberAddon (/tmp/testing-addon/node_modules/ember-cli/lib/broccoli/ember-addon.js:38:8)
```

**Comment by yankeeinlondon** [comment]
I've made quite a few updates tonight on UI-bootstrap, do you know which version you were using?

**Comment by KedneckInc** [comment]
Not exactly, so I'm running the test again.  The test was done just minutes before I posted the message.

**Comment by KedneckInc** [comment]
Just tried it with 0.0.21, same issue.

**Comment by KedneckInc** [comment]
```
TypeError: Cannot read property 'ui-bootstrap' of undefined
    at Class.included (/tmp/testing-addon/node_modules/ui-bootstrap/index.js:14:26)
    at /tmp/testing-addon/node_modules/ember-cli/lib/models/addon.js:245:32
    at Array.map (native)
    at Class.eachAddonInvoke (/tmp/testing-addon/node_modules/ember-cli/lib/models/addon.js:243:22)
    at Class.Addon.included (/tmp/testing-addon/node_modules/ember-cli/lib/models/addon.js:350:8)
    at EmberAddon.<anonymous> (/tmp/testing-addon/node_modules/ember-cli/lib/broccoli/ember-app.js:420:15)
    at Array.filter (native)
    at EmberAddon.EmberApp._notifyAddonIncluded (/tmp/testing-addon/node_modules/ember-cli/lib/broccoli/ember-app.js:415:45)
    at EmberAddon.EmberApp [as appConstructor] (/tmp/testing-addon/node_modules/ember-cli/lib/broccoli/ember-app.js:106:8)
    at new EmberAddon (/tmp/testing-addon/node_modules/ember-cli/lib/broccoli/ember-addon.js:38:8)
```

**Comment by KedneckInc** [comment]
I put in a console.log('number') between each line of the index.js file, and it (strangely enough) seems to be blowing in the following line:

```
    const o = app.options['ui-bootstrap'] || { useSASS: true };
```

**Comment by KedneckInc** [comment]
Okay... 'app.options' is undefined.  That explains the error message.  Now why is app.options undefined?

**Comment by KedneckInc** [comment]
Huh... known issue?

https://github.com/ember-cli/ember-cli/issues/3718

When I try the

```
this._super.included.apply(this,arguments)
```

I get the error where app.import is not defined.  Looks like this is a known issue with no good workaround for now.

**Comment by KedneckInc** [comment]
Might want to take a look at these:

parent addon: https://github.com/knownasilya/google-maps-markup/blob/master/index.js#L10
child: https://github.com/knownasilya/ember-palette/blob/master/index.js#L13

**Comment by yankeeinlondon** [comment]
Very odd, especially the need to change the child. It seems the way `parentAddon` is being passed into the included hook isn't fully dereferenced? Not sure I've fully grokked what's going on yet but we can make these changes and see how it works.

**Comment by yankeeinlondon** [comment]
I'm consuming `ui-bootstrap` in both an **addon** and an **app** and it seems work without this fix both for the ui-bootstrap component but also the cascading of `ember-cli-flash` (I had to send a pull request here so that it would cascade), `ember-modal`, and `ember-tooltips`. I think the example you're giving is sort of creating a problem that it needs to unwrap. 

Is the addon you're working on public? If so point me to it, I'd like to see how you're doing things.

**Comment by KedneckInc** [comment]
The test sequence described earlier is what I've been using to try and figure out what's going on.  The initial process involves no code changes on my part at all, only a move of the addon from the 'devDependencies' group to the 'dependencies' group.

According to what I've read, that _should_ be all that's needed.  While there is an 'addAddonToPackage' method, I had to search the code to find it, none of the instructions I've found said I should have to use it, although I did try it too.

I just looked in your package.json, and it appears that you're using ember-cli 2.3.0-beta.2.  I'll try switching to that, since I'm still on 2.2.0-beta.6.

**Comment by KedneckInc** [comment]
I've attached a copy of the script I built to test this issue, and a copy of the output of the last run I made (mildly edited).  I make no other changes.  I've tried both ember-cli 2.3.0-beta.2 and the just released 2.3.0.

[testscript.txt](https://github.com/lifegadget/ember-cli-bootstrap-sassy/files/134822/testscript.txt)
[log.txt](https://github.com/lifegadget/ember-cli-bootstrap-sassy/files/134823/log.txt)

**Comment by yankeeinlondon** [comment]
I realized that I wasn't seeing the full picture on my consumer app as I had `npm link`ed it up and it was giving me some false positives as a result. Anyway, have had very little bandwidth the past two days but I did make a change that worked for me. I'd be interested if it works for you (although the error you appear to be getting is not one I've gotten).

**Comment by yankeeinlondon** [comment]
latest is `ui-bootstrap@0.0.22`

**Comment by KedneckInc** [comment]
The error is basically the same, the name changed to 'uiBootstrap', instead of 'ui-bootstrap'.

**Comment by Sinled** [comment]
any updates on this issues?

still receiving 
`Cannot read property 'ember-cli-bootstrap-sassy' of undefined`
when trying to use with addon

```
ember-cli: 2.6.3
ember-cli-bootstrap-sassy: 0.5.3
```

**Comment by yankeeinlondon** [comment]
@Sinled happy to take a PR, I don't use this repo anymore so my bandwidth is limited (see above I'm using `ui-bootstrap` now). I will turn around any PR I receive promptly.
