### ISSUE TITLE
FastBoot compatibility

### ISSUE THREAD

**Issue by locks** [lifegadget/ember-cli-bootstrap-sassy#38]
I was trying to enable FastBoot on an application that uses this addon, but I am getting the following error message:

```
Installing FastBoot npm dependencies
jQuery is not defined
ReferenceError: jQuery is not defined
    at /path-to-app/fastboot-dist/fastboot/bower_components/bootstrap-sass/assets/javascripts/bootstrap/affix.js:162:1
```

Could you investigate if it's possible to make the addon work in FastBoot?
I've tried to configure the addon to not import the JavaScript files, but it didn't seem to make a difference.

**Comment by yankeeinlondon** [comment]
Interesting. Shouldn't need jquery. Not too fastboot savvy yet though.

**Comment by yankeeinlondon** [comment]
Any chance you could send me a PR? I am spending most of my time on BS 4.0 (ui-bootstrap) these days.

**Comment by locks** [comment]
I believe #39 should patch the problem, at least it isn't erroring out anymore. I can't confirm for sure how well it works because another addon is still preventing the page from rendering.

**Comment by lkgarrison** [comment]
@locks Thanks for your fix. However, I'm trying to install ember-cli-bootstrap-sassy but ember keeps installing bootstrap-sass instead. Why would this be happening, as bootstrap-sass doesn't have your fastboot fix?

![image](https://cloud.githubusercontent.com/assets/6644421/16500878/91c4294e-3ed4-11e6-95fc-2be58b14d04c.png)

**Comment by locks** [comment]
@lkgarrison doesn't ember-cli-bootstrap [depend on bootstrap-sass](https://github.com/lifegadget/ember-cli-bootstrap-sassy/blob/master/bower.json#L16)?

**Comment by lkgarrison** [comment]
@locks Yeah, but I'm not sure how to actually use bootstrap-**sassy** since it doesn't appear to have actually been installed anywhere. Maybe this is more of a question for @ksnyde

**Comment by yankeeinlondon** [comment]
Hi @lkgarrison, I've personally moved more to Bootstrap 4 where I'm updating `ui-bootstrap` as a similar addon to `bootstrap-sassy`. If that's not appropriate for you though I'm happy to accept a PR and I'll get that incorporated quickly.

**Comment by yankeeinlondon** [comment]
I'm not sure I understand your issue though. The main goal for `ember-cli-bootstrap-sassy` is to install the SASS version of Bootstrap 3. To leverage it you'd still need a SASS pre-processor in your project and this addon assumes you're using bootstrap-sass.

**Comment by zoltan-nz** [comment]
Ember-cli-bootstrap-sassy is FastBoot compatible now, so this issue could be closed, I think. ;)
