### ISSUE TITLE
How to change theme?

### ISSUE THREAD

**Issue by v3ss0n** [lifegadget/ember-cli-bootstrap-sassy#40]
How one can change theme without hacking internals? I watn to switch to material-bootstrap.

**Comment by yankeeinlondon** [comment]
The intent of this addon is just to incorporate the Bootstrap 3.0 CSS and JS. There is no support for theming currently. If you'd like to send me a PR I'd be happy to accept that. For reference, however, I am primarily using my `ui-bootstrap` addon these days. It uses BS 4.0. Still no theming though.

**Comment by zoltan-nz** [comment]
Is it still a requirement or the issue can be closed maybe?

**Comment by yankeeinlondon** [comment]
I am closing. V3ssOn if you are unhappy with this reach and let’s discuss.
