### ISSUE TITLE
Get rid of bower dependency

### ISSUE THREAD

**Issue by selvaa89** [lifegadget/ember-cli-bootstrap-sassy#44]
I am using this addon as a nested addon in my project. Since the bootstrap-sass is installed via bower, I have to execute the default blueprint from the parent addon to install the bower dependency.

So, if we use npm package instead of bower, it will be easy to nest this addon.

**Comment by yankeeinlondon** [comment]
Yeah that's a good idea and the approach i'm taking with all my new addons. I'm not actively using this one anymore but very happy to take a PR if you want to send me one.

> have a look at `ui-bootstrap` which is my Bootstrap 4.0 addon for an example of this

**Comment by selvaa89** [comment]
I will raise a PR. Could you look at the PR I have already raised?

**Comment by yankeeinlondon** [comment]
I believe your PR closed this, so closing issue.
