### ISSUE TITLE
Deprecation message on build in Ember 2.12: no JavaScript preprocessors were found for...

### ISSUE THREAD

**Issue by kliput** [lifegadget/ember-cli-bootstrap-sassy#46]
Hi,
The below deprecation message is shown when building Ember 2.12 app with ``ember-cli-bootstrap-sassy``:
```
DEPRECATION: Addon files were detected in
`/home/kliput/Onedata/onepanel-gui/src/node_modules/ember-cli-bootstrap-sassy/addon`,
but no JavaScript preprocessors were found for `ember-cli-bootstrap-sassy`.
Please make sure to add a preprocessor (most likely `ember-cli-babel`) to in
`dependencies` (NOT `devDependencies`) in `ember-cli-bootstrap-sassy`'s
`package.json`.
```
Best regards,
Jakub

**Comment by escobera** [comment]
@blimmer, hey there! are you waiting on some other issues to bump the version number?

**Comment by blimmer** [comment]
I'm not an owner on this project, but I think it got deployed as 0.5.6

https://github.com/lifegadget/ember-cli-bootstrap-sassy/pull/47#issuecomment-294910119

**Comment by kliput** [comment]
Just tried 0.5.6 and it's fixed. Thanks a lot :)

**Comment by yankeeinlondon** [comment]
Yes. Should be fixed.
