### ISSUE TITLE
Getting error on install

### ISSUE THREAD

**Issue by erichaus** [lifegadget/ember-cli-bootstrap-sassy#5]
remote: bower handlebars              extra-resolution Unnecessary resolution: handlebars#>= 2.0.0 < 3.0.0
remote: -----> Caching bower_components directory for future builds
remote: -----> Building Ember CLI application production distribution
remote:        version: 0.1.3
remote:
remote: /tmp/build_c483dcfcb84f7a1c49e134c9576795bc/node_modules/ember-cli-bootstrap-sassy/index.js:34
remote:             configMessage.push('some JS loaded [+'o.js.join(',')'+]');
remote:        Unexpected identifier
remote:        SyntaxError: Unexpected identifier

**Comment by erichaus** [comment]
points to the o in o.js.join

**Comment by akisvolanis** [comment]
made a new PR to fix some typos.

**Comment by yankeeinlondon** [comment]
this should be fixed now
