### ISSUE TITLE
Issue new release?

### ISSUE THREAD

**Issue by diasjorge** [lifegadget/ember-cli-bootstrap-sassy#51]
I'm currently seeing the following warning.

DEPRECATION: Addon files were detected in `/Users/jorge/development/spt/access/heimdall-admin/node_modules/ember-cli-bootstrap-sassy/addon`, but no JavaScript preprocessors were found for `ember-cli-bootstrap-sassy`. Please make sure to add a preprocessor (most likely `ember-cli-babel`) to in `dependencies` (NOT `devDependencies`) in `ember-cli-bootstrap-sassy`'s `package.json`.

I see this has been fixed in master, could it possible to issue a new version with the changes please?

**Comment by zoltan-nz** [comment]
This is fixed and the new release doesn't have any deprecation message, so this issue could be closed. ;)
