### ISSUE TITLE
glyphicons font files corrupted by ember build in 0.5.7

### ISSUE THREAD

**Issue by jmmorganMSTS** [lifegadget/ember-cli-bootstrap-sassy#55]
After upgrading to 0.5.7 the font files created under the `dist/` directory by `ember build` or served by `ember server` were not loading into browsers.

The installed source font file `node_modules/bootstrap-sass/assets/fonts/bootstrap/glyphicons-halflings-regular.woff` is 23424 bytes, a hex dump of the first few bytes is:
```
0000000: 774f 4646 0001 0000 0000 5b80 000f 0000  wOFF......[.....
0000010: 0000 b15c 0001 0000 0000 0000 0000 0000  ...\............
```

The post build font file `dist/fonts/bootstrap/glyphicons-halflings-regular.woff` is 43980 bytes and the hex dump of its start is:
```hex
0000000: 774f 4646 0001 0000 0000 5bef bfbd 000f  wOFF......[.....
0000010: 0000 0000 efbf bd5c 0001 0000 0000 0000  .......\........
```

It looks like all bytes above 7F are being incorrectly replaced with the Unicode Replacement Character. My guess would be that something is causing these binary files to be read and processes as ASCII or UTF-8 text. When an invalid byte in these encoding is encountered it is being replaced.

Locking the version of ember-cli-bootstrap-sassy to 0.5.6 resolves the issue.

**Comment by zoltan-nz** [comment]
The issue is here: https://github.com/lifegadget/ember-cli-bootstrap-sassy/blob/master/index.js#L92

broccoli-stew map mutate all files and alter the original font files also... I try with adding a filter.
https://github.com/stefanpenner/broccoli-stew/blob/master/lib/map.js#L26
